# Generated by Django 5.2.7 on 2025-10-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('teacher_ID', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('teacher_image', models.ImageField(blank=True, upload_to='teacher_images/')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
