# Generated by Django 5.2.7 on 2025-10-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student_ID',
            new_name='student_ID',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_inmage',
            new_name='student_image',
        ),
    ]
